package fr.sparna.rdf.skos.printer.cli.hierarchical;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import fr.sparna.commons.xml.fop.FopProvider;
import fr.sparna.rdf.rdf4j.toolkit.repository.RepositoryBuilderFactory;
import fr.sparna.rdf.rdf4j.toolkit.repository.init.ApplyUpdates;
import fr.sparna.rdf.skos.printer.DisplayPrinter;
import fr.sparna.rdf.skos.printer.cli.SkosPlayCliCommandIfc;
import fr.sparna.rdf.skos.printer.reader.BodyReader;
import fr.sparna.rdf.skos.printer.reader.ConceptBlockReader;
import fr.sparna.rdf.skos.printer.reader.HeaderAndFooterReader;
import fr.sparna.rdf.skos.printer.reader.HierarchicalDisplayGenerator;
import fr.sparna.rdf.skos.printer.schema.KosDocument;
import fr.sparna.rdf.skos.toolkit.SKOSRules;

public class Hierarchical implements SkosPlayCliCommandIfc {

	private Logger log = LoggerFactory.getLogger(this.getClass().getName());

	@Override
	public void execute(Object o) throws Exception {
		// retrieve arguments
		ArgumentsHierarchical args = (ArgumentsHierarchical)o;

		// TODO configure logging

		// lire le RDF d'input
		
		Repository inputRepository = RepositoryBuilderFactory.fromStringList(args.getInput()).get();

		try(RepositoryConnection connection = inputRepository.getConnection()) {
			// SKOS-XL
			ApplyUpdates.fromQueryReaders(SKOSRules.getSkosXl2SkosRuleset()).accept(connection);
			
			// build result document
			KosDocument document = new KosDocument();
			
			// build and set header
			HeaderAndFooterReader headerReader = new HeaderAndFooterReader(connection);
			headerReader.setApplicationString("Generated by SKOS Play!, sparna.fr");
			// on désactive complètement le header pour les PDF
			if(args.getFormat() != DisplayPrinter.Format.PDF) {
				// build and set header
				document.setHeader(headerReader.readHeader(
						args.getLang(),
						(args.getConceptScheme() != null)?SimpleValueFactory.getInstance().createIRI(args.getConceptScheme()):null
				));
			}
			// all the time, set footer
			document.setFooter(headerReader.readFooter(
					args.getLang(),
					(args.getConceptScheme() != null)?SimpleValueFactory.getInstance().createIRI(args.getConceptScheme()):null
			));		
			
			ConceptBlockReader cbReader = new ConceptBlockReader();
			cbReader.setSkosPropertiesToRead(HierarchicalDisplayGenerator.EXPANDED_SKOS_PROPERTIES);
			HierarchicalDisplayGenerator reader = new HierarchicalDisplayGenerator(connection, cbReader);
			BodyReader bodyReader = new BodyReader(reader);
			document.setBody(bodyReader.readBody(args.getLang(), (args.getConceptScheme() != null)?SimpleValueFactory.getInstance().createIRI(args.getConceptScheme()):null));
	
			// if debug needed
			// Marshaller m = JAXBContext.newInstance("fr.sparna.rdf.skos.printer.schema").createMarshaller();
			// m.setProperty("jaxb.formatted.output", true);
			// m.marshal(display, System.out);
			// m.marshal(document, new File("src/main/resources/alpha-index-output-test.xml"));
			
			if(args.getFopConfigPath() != null) {
				log.info("Will use FOP config file path : "+args.getFopConfigPath());
			}
	
			DisplayPrinter printer = new DisplayPrinter(new FopProvider(args.getFopConfigPath()));
			printer.setStyle(args.getStyle());
			printer.print(document, args.getOutput(), args.getLang(), args.getFormat());
		}
		
		// shutdown repos
		inputRepository.shutDown();

	}

}
