//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 05:44:57 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sparna.fr/index-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.sparna.rdf.solr.index.config.schema;
