PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

SELECT ?scheme (COUNT(?concept) AS ?conceptCount)
WHERE {
  ?scheme a skos:ConceptScheme .
  OPTIONAL {
	  ?concept a skos:Concept .
	  ?concept skos:inScheme ?scheme .
  }
} GROUP BY ?scheme