# S37 : skos:Collection is disjoint with each of skos:Concept and skos:ConceptScheme.
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
SELECT ?x 
WHERE {
	?x a skos:Collection .
	{
		{ ?x a skos:Concept . }
		UNION
		{ ?x a skos:ConceptScheme . }
	}
}