PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

ASK {
  { ?concept skos:broader|skos:narrower ?another . }
  UNION
  { 
  	?aCollection a skos:Collection .
  	?aCollection skos:member ?anotherCollection .
  	?aParentCollection a skos:Collection .
  }
}