# List the URIs and labels (optional) of all resources used as classes 
#
# @title	List of classes with their labels
# @tag 		model
# @tag 		SPARQL 1.0
# @see 		
# @param	
# 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?class ?label WHERE {
  [] a ?class
  OPTIONAL { ?class rdfs:label ?label }
} ORDER BY ?class ?label