# List the URIs of all resources used as properties, with their (optional) labels
#
# @title	List of properties with labels
# @tag 		model
# @tag		SPARQL 1.0
# @see 		
# @param	
# 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?property ?label WHERE {
  [] ?property ?value .
  OPTIONAL { ?property rdfs:label ?label }
} ORDER BY ?property ?label