# List the number of instances of each class, from largest to smallest
#
# @title	Number of instances per class
# @tag 		model
# @tag		SPARQL 1.1
# @see 		
# @param	
# 
SELECT DISTINCT ?class (COUNT(?x) AS ?numberOfInstances) WHERE {
  ?x a ?class .
}
GROUP BY ?class
ORDER BY DESC(?numberOfInstances)