# Les URIs de tous les partis politiques
#
# @title	Liste des partis politiques
# @tag		SPARQL 1.0
# @see 		
# @param	
# 
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpedia-fr: 	<http://fr.dbpedia.org/resource/>

SELECT ?parti
WHERE {
	?parti dbpedia-owl:wikiPageWikiLink dbpedia-fr:Catégorie:Parti_politique_français .
}