package fr.sparna.rdf.toolkit.select;

import java.io.PrintWriter;
import java.util.List;

import org.openrdf.model.URI;
import org.openrdf.query.BindingSet;
import org.openrdf.query.TupleQueryResultHandler;
import org.openrdf.query.TupleQueryResultHandlerException;

/**
 * Generates a (very) simple HTML page displaying the results of a SELECT query.
 * 
 * <p/>This handler needs to know the original SPARQL string to display it in the report.
 * 
 * <p/>To generate a report containing the results of multiple queries, you can associate
 * multiple SimpleHTMLReportHandler to the same PrintWriter and set the includeHTLMHeaders flag
 * to false so that the header and footer of the page will not be generated by each handler. Use
 * the static methods printHeader and printFooter to add them to the page.
 * 
 * @author Thomas Francart
 *
 */
public class SimpleHTMLReportHandler implements TupleQueryResultHandler {

	protected PrintWriter writer;
	protected List<String> bindingNames;
	// we need the sparql here only to display it in the report
	protected String sparql;
	// id of the sparql query (typically name of the SPARQL file)
	protected String sparqlID;

	public SimpleHTMLReportHandler(PrintWriter writer, String sparql, String sparqlID) {
		super();
		this.writer = writer;
		this.sparql = sparql;
		this.sparqlID = sparqlID;
	}

	public static void printHeader(PrintWriter writer) {
		writer.println("<html>");
		writer.println("<head>");
		writer.println("  <title>SPARQL Query Results</title>");
		writer.println("  <link href=\"bootstrap.min.css\" rel=\"stylesheet\">");
		writer.println("</head>");
		writer.println("<body><div class=\"container\">");
	}
	
	public static void printFooter(PrintWriter writer) {
		writer.println("</div></body>");
		writer.println("</html>");
	}
	
	@Override
	public void startQueryResult(List<String> bindingNames)
	throws TupleQueryResultHandlerException {	
		// keep binding names - because we need to make sure we process
		// them in the same order when processing query results
		this.bindingNames = bindingNames;
		
		writer.println("<h2>Query : "+this.sparqlID+"</h2>");
		writer.println("  <pre class=\"pre-scrollable\" id=\""+this.sparqlID+"\">"+this.sparql.replaceAll("<", "&lt;").replaceAll(">", "&gt;")+"</pre>");
		writer.println("<h2>Results</h2>");
		writer.println("  <div class=\"results\">");
		writer.println("\t<table class=\"table table-striped table-condensed\">");
		writer.println("\t<thead><tr>");
		for (String aBindingName : bindingNames) {
			writer.println("\t<th>"+aBindingName+"</th>");
		}
		writer.println("\t</tr></thead>");
		writer.println("\t<tbody>");
	}


	@Override
	public void handleSolution(BindingSet bs)
	throws TupleQueryResultHandlerException {
		writer.println("\t<tr>");
		for (String aBindingName : this.bindingNames) {
			if(bs.getValue(aBindingName) != null) {
				if(bs.getValue(aBindingName) instanceof URI) {
					writer.println("\t<td><a href=\""+bs.getValue(aBindingName).stringValue()+"\">"+bs.getValue(aBindingName).stringValue()+"</a></td>");
				} else {
					writer.println("\t<td>"+bs.getValue(aBindingName).stringValue()+"</td>");
				}				
			} else {
				writer.println("\t<td>&nbsp;</td>");
			}
		}
		writer.println("\t</tr>");
	}
	
	@Override
	public void endQueryResult() throws TupleQueryResultHandlerException {
		writer.println("\t</tbody></table>");
		writer.println("</div>");
		writer.println("<br/><br />");
	}

}
