# S24 (narrower) : skos:broaderTransitive and skos:narrowerTransitive are each instances of owl:TransitiveProperty.
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {
	?x skos:narrowerTransitive ?y .
} WHERE {
	?x skos:narrowerTransitive/skos:narrowerTransitive ?y .
}