//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 05:44:57 PM CEST 
//


package fr.sparna.rdf.solr.index.config.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" type="{http://www.sparna.fr/index-config}Source"/>
 *         &lt;element name="fieldMap" type="{http://www.sparna.fr/index-config}FieldMap"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityConfig", propOrder = {
    "source",
    "fieldMap"
})
public class EntityConfig {

    @XmlElement(required = true)
    protected Source source;
    @XmlElement(required = true)
    protected FieldMap fieldMap;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the fieldMap property.
     * 
     * @return
     *     possible object is
     *     {@link FieldMap }
     *     
     */
    public FieldMap getFieldMap() {
        return fieldMap;
    }

    /**
     * Sets the value of the fieldMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldMap }
     *     
     */
    public void setFieldMap(FieldMap value) {
        this.fieldMap = value;
    }

}
