PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?conceptScheme
WHERE {
	?conceptScheme a skos:ConceptScheme .
	OPTIONAL {
		?conceptScheme skos:prefLabel ?prefLabel .
		FILTER(lang(?prefLabel) = 'fr')
	}
}
ORDER BY ?prefLabel