PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?label ?prefLabel ?concept
WHERE {
	?concept a skos:Concept .
	{
		{
			# les prefLabels des concepts
			?concept skos:prefLabel ?label
			FILTER(lang(?label) = 'fr')
		} UNION {
			# les altLabels et leur pref
			?concept skos:altLabel ?label .
			?concept skos:prefLabel ?prefLabel .
			FILTER(lang(?label) = 'fr' && lang(?prefLabel) = 'fr')
		} UNION {
			# pas de prefLabel dans la langue ! on prend l'URI
			?concept a skos:Concept .
			FILTER NOT EXISTS {
				?concept skos:prefLabel ?nopref
				FILTER(lang(?nopref) = 'fr')
				BIND(str(?concept) as ?label)
			}
		}

	}
}
