# S24 (broader) : skos:broaderTransitive and skos:narrowerTransitive are each instances of owl:TransitiveProperty.
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
INSERT {
	?x skos:broaderTransitive ?y .
} WHERE {
	?x skos:broaderTransitive+ ?y .
}