//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 10:36:31 AM CET 
//


package fr.sparna.rdf.skos.printer.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represent an entire document. This is the root element.
 * 
 * <p>Java class for kosDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kosDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sparna.fr/thesaurus-display}kosDocumentMetadata" minOccurs="0"/>
 *         &lt;element ref="{http://www.sparna.fr/thesaurus-display}header"/>
 *         &lt;element ref="{http://www.sparna.fr/thesaurus-display}body"/>
 *         &lt;element ref="{http://www.sparna.fr/thesaurus-display}footer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kosDocument", propOrder = {
    "kosDocumentMetadata",
    "header",
    "body",
    "footer"
})
public class KosDocument {

    protected ElementContainer kosDocumentMetadata;
    @XmlElement(required = true)
    protected KosDocumentHeader header;
    @XmlElement(required = true)
    protected KosDocumentBody body;
    @XmlElement(required = true)
    protected KosDocumentFooter footer;
    @XmlAttribute(name = "writing-mode")
    protected String writingMode;

    /**
     * Gets the value of the kosDocumentMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ElementContainer }
     *     
     */
    public ElementContainer getKosDocumentMetadata() {
        return kosDocumentMetadata;
    }

    /**
     * Sets the value of the kosDocumentMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementContainer }
     *     
     */
    public void setKosDocumentMetadata(ElementContainer value) {
        this.kosDocumentMetadata = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link KosDocumentHeader }
     *     
     */
    public KosDocumentHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link KosDocumentHeader }
     *     
     */
    public void setHeader(KosDocumentHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link KosDocumentBody }
     *     
     */
    public KosDocumentBody getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link KosDocumentBody }
     *     
     */
    public void setBody(KosDocumentBody value) {
        this.body = value;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link KosDocumentFooter }
     *     
     */
    public KosDocumentFooter getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link KosDocumentFooter }
     *     
     */
    public void setFooter(KosDocumentFooter value) {
        this.footer = value;
    }
    

    public String getWritingMode() {
        return writingMode;
    }


    public void setWritingMode(String value) {
        this.writingMode = value;
    }

}
