//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 06:37:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sparna.fr/thesaurus-display", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.sparna.rdf.skos.printer.schema;
