# S48 : skosxl:Label is disjoint with each of skos:Concept, skos:ConceptScheme and skos:Collection.
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:<http://www.w3.org/2008/05/skos-xl#>
SELECT ?x 
WHERE {
	?x a skosxl:Label .
	{
		{?x a skos:Concept}
		UNION
		{?x a skos:ConceptScheme}
		UNION
		{?x a skos:Collection}
	}
}